name: Rust publish

on:
  release:
    published:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build -j 2 --all-targets && cargo build -j 2 --all-features --all-targets
    - name: Run tests
      run: cargo test -j 2 && cargo test -j 2 --all-features
    - name: Publish
      run: cargo publish -j 2 --dry-run
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES }}
