name: Rust publish

on:
  release:
    types: [published]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build -j 2 --all-features --all-targets
    - name: Run tests
      run: cargo test -j 2 --all-features
    - name: Publish packages
      run: cargo publish -j 2 --workspace
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES }}
        
